version: '3'

services:
  github-gists-api:
    build: .
    command: sh -c "uvicorn src.github_api_server:app --reload --port=8080 --host=0.0.0.0"
    platform: linux/amd64
    ports:
      - 8090:8080
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    volumes:
      - .:/app
